name: Test Patches
on:
    workflow_dispatch:
    schedule:
        # Every day at midnight
        - cron: 0 0 * * *

jobs:
    TestPlugins:
        if: github.repository == 'Vendicated/Vencord'
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
              if: ${{ github.event_name == 'schedule' }}
              with:
                  ref: dev

            - uses: actions/checkout@v3
              if: ${{ github.event_name == 'workflow_dispatch' }}

            - uses: pnpm/action-setup@v2 # Install pnpm using packageManager key in package.json

            - name: Use Node.js 19
              uses: actions/setup-node@v3
              with:
                  node-version: 19
                  cache: "pnpm"

            - name: Install dependencies
              run: |
                  pnpm install --frozen-lockfile
                  pnpm add puppeteer

            - name: Install Chromium
              uses: awalsh128/cache-apt-pkgs-action@a6c3917cc929dd0345bfb2d3feaf9101823370ad # v1.4.2
              with:
                packages: chromium-browser
                version: 1.0

            - name: Build web
              run: pnpm buildWeb --standalone --dev

            - name: Create Report
              timeout-minutes: 10
              run: |
                  export PATH="$PWD/node_modules/.bin:$PATH"
                  export CHROMIUM_BIN=$(which chromium-browser)
                  echo "CHROMIUM_BIN=$CHROMIUM_BIN"

                  esbuild scripts/generateReport.ts > dist/report.mjs
                  node dist/report.mjs >> $GITHUB_STEP_SUMMARY
              env:
                  DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
                  DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

            - name: Create Report (Canary)
              timeout-minutes: 10
              if: success() || failure() # even run if previous one failed
              run: |
                  export PATH="$PWD/node_modules/.bin:$PATH"
                  export CHROMIUM_BIN=$(which chromium-browser)
                  export USE_CANARY=true

                  esbuild scripts/generateReport.ts > dist/report.mjs
                  node dist/report.mjs >> $GITHUB_STEP_SUMMARY
              env:
                  DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
                  DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
